# Generated by Django 4.0.4 on 2022-07-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaraunt',
            new_name='restaurant',
        ),
    ]
