# Generated by Django 4.0.4 on 2022-07-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_restaraunt_menu_restaurant'),
        ('orders', '0003_rename_restaraunt_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drinks',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
