# Generated by Django 4.0.4 on 2022-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drinks',
            field=models.CharField(max_length=150),
        ),
    ]
