# Generated by Django 4.0.4 on 2022-07-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
