# Generated by Django 4.0.4 on 2022-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
