# Generated by Django 4.0.4 on 2022-07-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_table_occupied'),
        ('reservations', '0007_reservation_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
