# Generated by Django 4.0.4 on 2022-07-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_rename_table_reservation_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='table_id',
            new_name='table',
        ),
    ]
