# Generated by Django 4.0.4 on 2022-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_rename_table_id_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='Rogers', max_length=50),
            preserve_default=False,
        ),
    ]
