# Generated by Django 4.0.4 on 2022-07-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservation_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='last_name',
            new_name='user_name',
        ),
    ]
