# Generated by Django 4.0.4 on 2022-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_rename_last_name_reservation_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
