# Generated by Django 4.0.4 on 2022-08-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='info',
            field=models.CharField(max_length=300),
        ),
    ]
