# Generated by Django 4.0.4 on 2022-07-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table',
            new_name='Restaurant',
        ),
    ]
