# Generated by Django 4.0.4 on 2022-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_remove_table_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Restaurant',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Seats',
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
