# Generated by Django 4.0.4 on 2022-07-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_rename_restaurant_table_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
