# Generated by Django 4.0.4 on 2022-08-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_delete_customer'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=50)),
                ('restaurant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
