# Generated by Django 4.0.4 on 2022-07-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_menu'),
        ('menu', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
