# Generated by Django 4.0.4 on 2022-07-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_menu'),
        ('menu', '0004_menu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaraunt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
