# Generated by Django 4.0.4 on 2022-07-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menu_restaurant_menu_restaraunt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaraunt',
            new_name='restaurant',
        ),
    ]
